spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:movieplay
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  security:
    user:
      name: admin
      password: admin
google:
  client-id: 724452454631-jvu3g96eoqa2hpn68irogbk1er7lplfq.apps.googleusercontent.com

tmdb:
  api:
    key: 401cdbb25f2bf2ecbb11192e86d3e57e
